schemaVersion: 2.2.0
metadata:
  name: hugo
components:
  - container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      sourceMapping: /projects
    name: hugo
commands:
  - id: install-hugo
    exec:
      commandLine: wget -qO- https://github.com/gohugoio/hugo/releases/download/v0.120.4/hugo_0.120.4_Linux-64bit.tar.gz | ( cd $HOME/.local/bin ; tar xvfz - hugo ) 
      label: install hugo
