baseURL = 'https://OPP-2023-lab-instruction.github.io/'
languageCode = 'en-us'
title = 'Openshift platform plus 2023 Lab'

theme = 'hugo-theme-learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "red"
openshift_domain = "cluster-GUID.GUID.sandboxID.opentlc.com"
